### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by larasatiayudia** [rasyidstat/liburrr#1]
hi, i have a problem when installing. The error message:

*** arch - i386
Error: package or namespace load failed for 'liburrr' in namespaceExport(ns, exports):
 undefined exports: is_long_weekend
Error: loading failed
Execution halted
*** arch - x64
Error: package or namespace load failed for 'liburrr' in namespaceExport(ns, exports):
 undefined exports: is_long_weekend
Error: loading failed
Execution halted
ERROR: loading failed for 'i386', 'x64'
* removing 'D:/user/R/win-library/3.6/liburrr'
Error: Failed to install 'liburrr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/AppData/Local/Temp/Rtmp2X5AHe/file12f865b55bea/liburrr_0.1.1.tar.gz’ had non-zero exit status

I think you should update your namespace

**Comment by rasyidstat** [comment]
Fixed
